package com.mybatis.web.mapper;

import com.mybatis.web.entity.SysDict;
import java.util.List;

import org.apache.ibatis.session.RowBounds;

public interface SysDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Nov 30 09:48:07 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Nov 30 09:48:07 CST 2018
     */
    int insert(SysDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Nov 30 09:48:07 CST 2018
     */
    SysDict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Nov 30 09:48:07 CST 2018
     */
    List<SysDict> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Nov 30 09:48:07 CST 2018
     */
    int updateByPrimaryKey(SysDict record);
    
    /**
     *   ∑÷“≥≤È—Ø
     * @param sysDict
     * @param rowBounds
     * @return
     */
    List<SysDict> selectBySysDict(SysDict sysDict, RowBounds rowBounds );
}